version: '3'

volumes:
  postgres_data: {}

services:
  api:
    container_name: thegatheringhub-container
    build:
      context: ./
      dockerfile: ./docker_compose/api/Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres
    build:
      context: ./
      dockerfile: ./docker_compose/postgres/Dockerfile
    expose: 
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
